import { PortfolioData } from "./types";

export const defaultPortfolioData: PortfolioData = {
  name: "Abhijit Rathod",
  role: "Frontend Developer | CSE Student",
  intro:
    "I build clean, responsive, and modern web interfaces. Currently focused on HTML, CSS, JavaScript, React, and Next.js while building real-world frontend projects.",
  about:
    "I’m a Computer Science Engineering student and an aspiring frontend developer. I enjoy building modern websites, dashboards, and user-friendly interfaces. Right now, I’m focused on improving my frontend skills, creating strong projects, and preparing for frontend developer job opportunities.",
  location: "Karnataka, India",
  availability: "Open to freelance and frontend opportunities",
  github: "https://github.com/abirxx12",
  linkedin: "https://linkedin.com/",
  email: "rathodabhi030@gmail.com",
  profileImage: "",
  resume: "",
  heroStats: [
    { label: "Projects Built", value: "10+" },
    { label: "Skills", value: "9+" },
    { label: "Focus", value: "Frontend" },
    { label: "Availability", value: "Open" },
  ],
  skills: [
    { id: "frontend", name: "Frontend", items: ["HTML", "CSS", "JavaScript", "React", "Next.js"] },
    { id: "styling", name: "Styling", items: ["Tailwind CSS", "Responsive Design", "UI Systems"] },
    { id: "tools", name: "Tools", items: ["Git", "GitHub", "Vercel", "Figma"] },
    { id: "learning", name: "Currently Learning", items: ["TypeScript", "Accessibility", "Performance"] },
  ],
  projects: [
    {
      id: "portfolio-website",
      title: "Portfolio Website",
      shortDescription: "A polished personal portfolio with hidden admin editing and dynamic content.",
      fullDescription: "A polished portfolio website designed to showcase frontend skills, featured projects, and editable content through a hidden admin panel.",
      techStack: ["Next.js", "TypeScript", "Tailwind CSS"],
      github: "https://github.com/abirxx12",
      live: "#",
      image: "",
      category: "Frontend",
      status: "Completed",
      featured: true,
      date: "2026",
      order: 1,
    },
    {
      id: "trading-dashboard",
      title: "Trading Dashboard UI",
      shortDescription: "A clean dashboard UI concept focused on usability and responsive layouts.",
      fullDescription: "A responsive trading dashboard concept with modern cards, clear hierarchy, and a premium dark interface.",
      techStack: ["React", "Tailwind CSS"],
      github: "https://github.com/abirxx12",
      live: "#",
      image: "",
      category: "Dashboard",
      status: "Completed",
      featured: true,
      date: "2025",
      order: 2,
    },
    {
      id: "ecommerce-frontend",
      title: "E-commerce Frontend",
      shortDescription: "A modern shopping experience with product cards and responsive sections.",
      fullDescription: "A modern frontend for an e-commerce experience focused on responsive design and product discovery.",
      techStack: ["React", "CSS", "API Integration"],
      github: "https://github.com/abirxx12",
      live: "#",
      image: "",
      category: "UI",
      status: "In Progress",
      featured: false,
      date: "2025",
      order: 3,
    },
  ],
  education: [
    {
      id: "education-1",
      institute: "Computer Science Engineering Student",
      degree: "B.Tech / CSE",
      location: "India",
      startYear: "2023",
      endYear: "2027",
      score: "Ongoing",
      description: "Building strong foundations in programming, web development, and problem solving.",
    },
  ],
  experience: [
    {
      id: "experience-1",
      company: "Self Directed",
      role: "Frontend Developer",
      startDate: "2024",
      endDate: "Present",
      location: "Remote",
      description: "Creating modern frontend interfaces and learning production-ready development practices.",
      technologies: "HTML, CSS, JavaScript, React, Next.js",
    },
  ],
  theme: {
    accentColor: "#38bdf8",
  },
};